### ISSUE TITLE
Cannot connect to OPC server

### ISSUE THREAD

**Issue by avnet78** [godsharp/opcsample#7]
I have registered the opcdaauto.dll and now I am seeing another exception in the logs:

System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at OPCAutomation.IOPCAutoServer.Connect(String ProgID, Object Node)
   at GodSharp.Opc.Da.OpcAutomationClient.OnConnect()
   at GodSharp.Opc.Da.OpcDaClient.Connect()
   at RigCLOUDOPCDA.Reader.Program.EstablishOPCConnection(Boolean disconnect) 

Please advise.

**Comment by seayxu** [comment]
Have you solved it?

**Comment by RafaelxFernandes** [comment]
Any updates on this?

**Comment by seayxu** [comment]
> Any updates on this?

Not yet,need more info, like server,env ...
